### PR TITLE
Merge the "Simplifying NoSQL Database Integration with Jakarta NoSQL" blogpost into draft

### PR DESCRIPTION
**Pull request by dearrudam**
Ref: #https://github.com/OpenLiberty/blogs/issues/3536

### CODE REVIEW

**Comment by dearrudam** [comment]
@otaviojava, could you review the content of this blogpost? It's working in progress yet... I'll be open to suggestions

**Comment by dearrudam** [comment]
@fabio-franco, feel free to take a look at it! I'm open to suggestions!

**Comment by fabio-franco** [comment]
@dearrudam , that is an amazing work done so far! Until the end of this week, I will review it and the code you sent for review and let you know. You rock!

**Review by fabio-franco — APPROVED** [review]

**Comment by dearrudam** [comment]
@fabio-franco could you review this first completed version of this blog post?

**Comment by dearrudam** [comment]
@otaviojava could you review this first completed version of this blog post?

**Comment by dearrudam** [comment]
@eldermoraes, could you review this blog post?

**Comment by fabio-franco** [comment]
Hi @rhagarty, can you help us with the review and feedback of the draft for the blog post? Thank you!

**Comment by fabio-franco** [comment]
Hi @yeekangc, @lauracowen, and @GraceJansen! Can you help us with the review and feedback on the draft for the blog post? Also, any feedback on https://github.com/OpenLiberty/sample-jakartaNoSQL-game/pull/1 would be greatly appreciated. Thank you!

**Comment by gljrobinson** [comment]
Hey @fabio-franco, happy to help review this. It would be really helpful if you could merge this PR into draft so we can see how it renders on the Open Liberty site. Once you've done this, please open a PR to staging and we can create review comments in this. Thanks so much.

**Pull request merged**
